//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenViewer.API.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodexoCall
    {
        public int SodexoCallId { get; set; }
        public int ContactID { get; set; }
        public string SiteNo { get; set; }
        public string CustNo { get; set; }
        public string CustName { get; set; }
        public string SiteAddress1 { get; set; }
        public string SiteAddress2 { get; set; }
        public string SiteCity { get; set; }
        public string SiteState { get; set; }
        public string SiteZip { get; set; }
        public string CallType { get; set; }
        public string NatureofCall { get; set; }
        public string Dept { get; set; }
        public string Division { get; set; }
        public Nullable<bool> OvertimeApproved { get; set; }
        public string PONumbrt { get; set; }
        public string NTX { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string VendorNumber { get; set; }
        public string Priority { get; set; }
        public string ProblemCode { get; set; }
        public string CallerPhone { get; set; }
        public string CallerEmail { get; set; }
        public string WorkOrderID { get; set; }
        public string CallerName { get; set; }
        public string CallerTitle { get; set; }
        public string SiteName { get; set; }
    }
}
