//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenViewer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactRecord()
        {
            this.Activities = new HashSet<Activity>();
            this.ContactAttributes = new HashSet<ContactAttribute>();
            this.ContactNavigations = new HashSet<ContactNavigation>();
            this.ContactRecordDetails = new HashSet<ContactRecordDetail>();
            this.ContactVariables = new HashSet<ContactVariable>();
            this.Orders = new HashSet<Order>();
            this.IDRServiceQueues = new HashSet<IDRServiceQueue>();
            this.ContactTasks = new HashSet<ContactTask>();
        }
    
        public int ContactId { get; set; }
        public string ClientCallId { get; set; }
        public string ANI { get; set; }
        public Nullable<System.DateTime> CallStartDateTime { get; set; }
        public Nullable<System.DateTime> CallEndDateTime { get; set; }
        public string CallState { get; set; }
        public string DispositionCode { get; set; }
        public string ProjectName { get; set; }
        public string LeadRecordId { get; set; }
        public string Notes { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserId { get; set; }
        public string ClientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAttribute> ContactAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactNavigation> ContactNavigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactRecordDetail> ContactRecordDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactVariable> ContactVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDRServiceQueue> IDRServiceQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactTask> ContactTasks { get; set; }
    }
}
