//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenViewer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScreenPlayCRMEntities : DbContext
    {
        public ScreenPlayCRMEntities()
            : base("name=ScreenPlayCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityAttribute> ActivityAttributes { get; set; }
        public virtual DbSet<ContactAttribute> ContactAttributes { get; set; }
        public virtual DbSet<ContactNavigation> ContactNavigations { get; set; }
        public virtual DbSet<ContactRecord> ContactRecords { get; set; }
        public virtual DbSet<ContactRecordDetail> ContactRecordDetails { get; set; }
        public virtual DbSet<ContactVariable> ContactVariables { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<IDRServiceQueue> IDRServiceQueues { get; set; }
        public virtual DbSet<ContactTask> ContactTasks { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LeadRecord> LeadRecords { get; set; }
        public virtual DbSet<LeadRecordAttribute> LeadRecordAttributes { get; set; }
    }
}
