//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenViewer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptTask
    {
        public int ScriptTaskID { get; set; }
        public string TaskDesc { get; set; }
        public string TaskType { get; set; }
        public string TaskColor { get; set; }
        public string WorkStartTime { get; set; }
        public string WorkEndTime { get; set; }
        public string DefaultView { get; set; }
        public string Timezone { get; set; }
        public bool ShowStartDate { get; set; }
        public bool ShowEndDate { get; set; }
        public bool ShowAllDay { get; set; }
        public bool ShowRepeatRule { get; set; }
        public bool IsMultiUserTask { get; set; }
        public bool DeleteEnabled { get; set; }
        public bool UpdateEnabled { get; set; }
        public string Width { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
        public string FilterTask { get; set; }
        public Nullable<bool> AddCustomButton { get; set; }
        public string CustomButtonText { get; set; }
        public string CustomButtonURL { get; set; }
        public Nullable<int> EndTimeMinute { get; set; }
    }
}
