//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class script {
    
    private string eventField;
    
    private string bindControlIDField;
    
    private string bindTypeField;
    
    private string bindClientFunctionField;
    
    private string bindAPIField;
    
    private string bindDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BindControlID {
        get {
            return this.bindControlIDField;
        }
        set {
            this.bindControlIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BindType {
        get {
            return this.bindTypeField;
        }
        set {
            this.bindTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BindClientFunction {
        get {
            return this.bindClientFunctionField;
        }
        set {
            this.bindClientFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BindAPI {
        get {
            return this.bindAPIField;
        }
        set {
            this.bindAPIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BindData {
        get {
            return this.bindDataField;
        }
        set {
            this.bindDataField = value;
        }
    }
}

/// <remarks/>

public partial class NewDataSet {
    
    private script[] itemsFieldData;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("script")]
public script[] ItemsFieldData
{
  get { return itemsFieldData; }
  set { itemsFieldData = value; }
}
    
  
   
}
